### ISSUE TITLE
"IndentationError: unindent does not match any outer indentation level" Error message in setup

### ISSUE THREAD

**Issue by oncee** [trustedsec/artillery#75]
sudo ./setup.py
Traceback (most recent call last):
  File "./setup.py", line 7, in <module>
    from src.core import *
  File "/home/oncee/Desktop/artillery-master/src/core.py", line 503
    return
         ^
IndentationError: unindent does not match any outer indentation level

 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by TheAngryByrd** [comment]
The project has moved to https://github.com/BinaryDefense/artillery.  Try the latest from there and it's still a problem please open an issue there.  

Thanks!
